### ISSUE TITLE
support upgrade from the local web server?

### ISSUE THREAD

**Issue by Tao173** [HomeACcessoryKid/life-cycle-manager#33]
Does it support upgrading main.bin from the local web server, because I can't access the file through github normally. I built a local web server using nginx.

**Comment by HomeACcessoryKid** [comment]
yes and no

It supports loading a new copy of otaboot.bin  and only that. After that you should be able to load main.bin in the regular way.

see the section [New feature version 2](https://github.com/HomeACcessoryKid/life-cycle-manager#new-feature-version-2) in the readme.

trigger 12 times, and provide the directory where otaboot.bin and otaboot.bin.sig are located in your webserver.

In the flow diagram, it is where the dotted line is for the emergency mode.

**Comment by Tao173** [comment]
Thanks for your answer.
If I understand correctly, otaboot.bin supports local upgrade , But what I need to upgrade is main.bin, I don't want to use github api to upgrade, because the network is not always accessible for me.

**Comment by HomeACcessoryKid** [comment]
My instantiation of LCM does not support standalone operation.

And the phrase would have to be "local upgrade supports otaboot.bin", not the other way around.

However, you can fork LCM, change which server is used, potentially remove the checksum parts and tweak otherwise and it could work for you. But all that work is on you.

**Comment by Tao173** [comment]
OK,I will try.
